# Generated by Django 4.0.4 on 2022-04-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_soil'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='soils',
            field=models.ManyToManyField(to='main_app.soil'),
        ),
    ]
